image: node:latest

stages:
  - build
  - deploy

build: 
  type: build
  stage: build
  image: node:alpine
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master
  
production:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master